extraction:
  cpp:
    after_prepare: 
      - python report.py 102
  cobol:
    after_prepare: 
      - python report.py 102
  csharp:
    after_prepare: 
      - python report.py 102
  java:
    after_prepare: 
      - python report.py 102
  javascript:
    after_prepare: 
      - python report.py 102
  python:
    after_prepare: 
      - python report.py 102
